services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_API_URL: http://backend:8080
      NEXT_PUBLIC_RUSTFS_PUBLIC_ENDPOINT: http://localhost:9000
      RUSTFS_BUCKET: masaladb
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
